In [1]:
import pandas as pd
import numpy as np
import os
from datetime import datetime
import math
import csv
import re

from dotenv import load_dotenv

# Scraping

### env variables

In [2]:
load_dotenv()

BASE_PATH = os.environ['BASE_PATH']
RESULTS_PATH = os.environ['RESULTS_PATH']
RANKINGS_PATH = os.environ['RANKINGS_PATH']
SPECIALITY_RANKINGS_PATH = os.environ['SPECIALITY_RANKINGS_PATH']
TEAMS_PATH = os.environ['TEAMS_PATH']
CALENDARS_PATH = os.environ['CALENDARS_PATH']
STARTLISTS_PATH = os.environ['STARTLISTS_PATH']
RACERESULTS_PATH = os.environ['RACERESULTS_PATH']
IMG_PATH = os.environ['IMG_PATH']
RIDERSTATS_PATH = os.environ['RIDERSTATS_PATH']
RACENAMES_PATH = os.environ['RACENAMES_PATH']

# Load data

In [3]:
rider_names = list(pd.read_csv(os.path.join(BASE_PATH, 'rider_names.csv')))

# Goals

- Compute average speed for top professionals in ITT for given type of course (distance, elevation)
- select which are the top professionals
- select junior riders
- compute junior riders ITT speed and compare
- for successful ITT specialists, visualize progression from junior to pro

# Top pros

- top 20 riders by PCS points

In [4]:
year = '2022'
date = '2022-03-25'

itt_ranking = pd.read_csv(os.path.join(SPECIALITY_RANKINGS_PATH, 'ITT', year, date, 'itt.csv'))
itt_ranking.Rider.iloc[:5]

0         Küng Stefan
1       Ganna Filippo
2      Asgreen Kasper
3    Bissegger Stefan
4       Roglič Primož
Name: Rider, dtype: object

In [5]:
def normalize_name(name):
    
    return '-'.join(reversed(name.split(' '))).lower()

In [6]:
year = '2022'
rider_name = normalize_name(itt_ranking.Rider[0])

df = pd.read_csv(os.path.join(RESULTS_PATH, rider_name, f'{year}.csv'), encoding='UTF-8')

In [7]:
df

,Date,Result,GC,Race,Distance,PointsPCS,PointsUCI
0,25.03,3.0,NaN,E3 Saxo Bank Classic (1.UWT),203.9,110.0,260.0
1,06.03 » 13.03,NaN,NaN,Paris - Nice (2.UWT),NaN,NaN,NaN
2,NaN,10.0,NaN,Points classification,NaN,NaN,NaN
3,NaN,21.0,NaN,General classification,NaN,18.0,20.0
4,13.03,6.0,NaN,Stage 8 - Nice › Nice,115.6,7.0,NaN
5,12.03,38.0,33.0,Stage 7 - Nice › Col de Turini,155.2,NaN,NaN
6,11.03,66.0,32.0,Stage 6 - CourthÃ©zon › Aubagne,213.6,NaN,NaN
7,10.03,49.0,26.0,Stage 5 - Saint-Just-Saint-Rambert › Saint-Sau...,188.8,NaN,NaN
8,09.03,4.0,24.0,Stage 4 (ITT) - DomÃ©rat › MontluÃ§on,13.4,13.0,NaN
9,08.03,40.0,45.0,Stage 3 - Vierzon › Dun-le-Palestel,190.8,NaN,NaN
10,07.03,15.0,50.0,Stage 2 - Auffargis › OrlÃ©ans,159.2,NaN,NaN
11,06.03,98.0,98.0,Stage 1 - Mantes-la-Ville › Mantes-la-Ville,159.8,NaN,NaN
12,27.02,47.0,NaN,Kuurne - Bruxelles - Kuurne (1.Pro),195.1,NaN,NaN
13,26.02,12.0,NaN,Omloop Het Nieuwsblad ME (1.UWT),204.2,34.0,35.0
14,16.02 » 20.02,NaN,NaN,Volta ao Algarve em Bicicleta (2.Pro),NaN,NaN,NaN
15,NaN,7.0,NaN,General classification,NaN,55.0,60.0
16,20.02,11.0,NaN,Stage 5 - Lagoa › MalhÃ£o (LoulÃ©),173.0,NaN,NaN
17,19.02,2.0,5.0,Stage 4 (ITT) - Vila Real de Santo AntÃ³nio › ...,32.2,18.0,10.0
18,18.02,30.0,19.0,Stage 3 - AlmodÃ´var › Faro,211.4,NaN,NaN
19,17.02,19.0,19.0,Stage 2 - Albufeira › FÃ³ia (Monchique),182.4,NaN,NaN
20,16.02,41.0,42.0,Stage 1 - PortimÃ£o › Lagos,199.1,NaN,NaN

### Correct encoding errors

In [8]:
replace_dict = {'Ã©': 'é', 
              'Ã§': 'ç', 
              'Ã³': 'ó',
              'Ã´': 'ô',
              'Ã£': 'ã',
              'Ã': 'É'}

df.replace(replace_dict, regex=True, inplace=True)

### Clean data

In [12]:
import sys
sys.path.insert(1, '../scripts')

In [13]:
from data_prep_utils import *

In [14]:
clean_data(df, rider_name, year, save=False)

,FromDate,Result,GC,Race,Distance,PointsPCS,PointsUCI,Type,ToDate,RaceName
0,2022-03-25,3,NaN,E3 Saxo Bank Classic (1.UWT),203.9,110.0,260.0,OneDayRace,2022-03-25,E3 Saxo Bank Classic (1.UWT)
1,2022-03-06,0,NaN,Paris - Nice (2.UWT),NaN,NaN,NaN,StageRace,2022-03-13,Paris - Nice (2.UWT)
2,2022-03-13,10,NaN,Points classification,NaN,NaN,NaN,StageRace,2022-03-13,Paris - Nice (2.UWT)
3,2022-03-13,21,NaN,General classification,NaN,18.0,20.0,StageRace,2022-03-13,Paris - Nice (2.UWT)
4,2022-03-13,6,NaN,Stage 8 - Nice › Nice,115.6,7.0,NaN,StageRace,2022-03-13,Paris - Nice (2.UWT)
5,2022-03-12,38,33.0,Stage 7 - Nice › Col de Turini,155.2,NaN,NaN,StageRace,2022-03-12,Paris - Nice (2.UWT)
6,2022-03-11,66,32.0,Stage 6 - Courthézon › Aubagne,213.6,NaN,NaN,StageRace,2022-03-11,Paris - Nice (2.UWT)
7,2022-03-10,49,26.0,Stage 5 - Saint-Just-Saint-Rambert › Saint-Sau...,188.8,NaN,NaN,StageRace,2022-03-10,Paris - Nice (2.UWT)
8,2022-03-09,4,24.0,Stage 4 (ITT) - Domérat › Montluçon,13.4,13.0,NaN,StageRace,2022-03-09,Paris - Nice (2.UWT)
9,2022-03-08,40,45.0,Stage 3 - Vierzon › Dun-le-Palestel,190.8,NaN,NaN,StageRace,2022-03-08,Paris - Nice (2.UWT)
10,2022-03-07,15,50.0,Stage 2 - Auffargis › Orléans,159.2,NaN,NaN,StageRace,2022-03-07,Paris - Nice (2.UWT)
11,2022-03-06,98,98.0,Stage 1 - Mantes-la-Ville › Mantes-la-Ville,159.8,NaN,NaN,StageRace,2022-03-06,Paris - Nice (2.UWT)
12,2022-02-27,47,NaN,Kuurne - Bruxelles - Kuurne (1.Pro),195.1,NaN,NaN,OneDayRace,2022-02-27,Kuurne - Bruxelles - Kuurne (1.Pro)
13,2022-02-26,12,NaN,Omloop Het Nieuwsblad ME (1.UWT),204.2,34.0,35.0,OneDayRace,2022-02-26,Omloop Het Nieuwsblad ME (1.UWT)
14,2022-02-16,0,NaN,Volta ao Algarve em Bicicleta (2.Pro),NaN,NaN,NaN,StageRace,2022-02-20,Volta ao Algarve em Bicicleta (2.Pro)
15,2022-02-20,7,NaN,General classification,NaN,55.0,60.0,StageRace,2022-02-20,Volta ao Algarve em Bicicleta (2.Pro)
16,2022-02-20,11,NaN,Stage 5 - Lagoa › Malhão (Loulé),173.0,NaN,NaN,StageRace,2022-02-20,Volta ao Algarve em Bicicleta (2.Pro)
17,2022-02-19,2,5.0,Stage 4 (ITT) - Vila Real de Santo António › T...,32.2,18.0,10.0,StageRace,2022-02-19,Volta ao Algarve em Bicicleta (2.Pro)
18,2022-02-18,30,19.0,Stage 3 - Almodôvar › Faro,211.4,NaN,NaN,StageRace,2022-02-18,Volta ao Algarve em Bicicleta (2.Pro)
19,2022-02-17,19,19.0,Stage 2 - Albufeira › Fóia (Monchique),182.4,NaN,NaN,StageRace,2022-02-17,Volta ao Algarve em Bicicleta (2.Pro)
20,2022-02-16,41,42.0,Stage 1 - Portimão › Lagos,199.1,NaN,NaN,StageRace,2022-02-16,Volta ao Algarve em Bicicleta (2.Pro)

### Select ITTs

In [15]:
df[df.Race.str.contains('ITT|Chrono des Nations')]

,FromDate,Result,GC,Race,Distance,PointsPCS,PointsUCI,Type,ToDate,RaceName
8,2022-03-09,4,24.0,Stage 4 (ITT) - Domérat › Montluçon,13.4,13.0,NaN,StageRace,2022-03-09,Paris - Nice (2.UWT)
17,2022-02-19,2,5.0,Stage 4 (ITT) - Vila Real de Santo António › T...,32.2,18.0,10.0,StageRace,2022-02-19,Volta ao Algarve em Bicicleta (2.Pro)

In [21]:
for race in df[df.Race.str.contains('ITT|Chrono des Nations')].iterrows():
    print(race[1].RaceName)

Paris - Nice (2.UWT)
Volta ao Algarve em Bicicleta (2.Pro)